/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.com;
import java.awt.print.PrinterException;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

    class grade {

        public grade() {
        }
    }
/**
 *
 * @author USER
 */
public class AdminWorkFrame extends javax.swing.JFrame {

    /**
     * Creates new form WorkFrame
     */
    public AdminWorkFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taPrint = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        cbYear = new javax.swing.JComboBox<>();
        cbMajor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtRno = new javax.swing.JTextField();
        btnStushowres = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnStuMarks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Admin Working Area");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        taPrint.setColumns(20);
        taPrint.setRows(5);
        jScrollPane1.setViewportView(taPrint);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        cbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Year", "First Year", "Second Year", "Third Year", "Fourth Year", "Fifth Year" }));
        cbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbYearActionPerformed(evt);
            }
        });

        cbMajor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Major", "SE", "KE", "BIS", "HPC", "CN", "CS" }));
        cbMajor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMajorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Enter Roll No:");

        txtRno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRnoActionPerformed(evt);
            }
        });

        btnStushowres.setText("Show Student Result");
        btnStushowres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStushowresActionPerformed(evt);
            }
        });

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnStuMarks.setText("Show Student Marks by Roll Number");
        btnStuMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStuMarksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(cbMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnStushowres)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtRno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnStuMarks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(txtRno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStuMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStushowres, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStushowresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStushowresActionPerformed
        
        try {
            String sql = "";
            
            Connection  con = DriverManager.getConnection("jdbc:sqlite:D:\\sqlite\\studentdb.db");
            Statement st = con.createStatement();
            String stumajor = (String) cbMajor.getSelectedItem();
            
            taPrint.setText(null);
            
            
            if (cbYear.getSelectedItem().equals("First Year")) {
                sql = "SELECT fstudent.Stu_rno, fstudent.stu_name,  FirstMarks.Grade, FirstMarks.Remark "
                        + "FROM fstudent, FirstMarks "
                        + "WHERE fstudent.Stu_rno = FirstMarks.Stu_rno AND fstudent.major='" + stumajor + "'";
            } else if (cbYear.getSelectedItem().equals("Second Year")) {
                sql = "SELECT S sstudent.Stu_rno, sstudent.stu_name,  SecondMarks.Grade, SecondMarks.Remark "
                        + "FROM sstudent, SecondMarks "
                        + "WHERE sstudent.Stu_rno = SecondMarks.Stu_rno AND sstudent.major='" + stumajor + "'";
            } else if (cbYear.getSelectedItem().equals("Third Year")) {
                sql = "SELECT  tstudent.Stu_rno, tstudent.stu_name,  ThirdMarks.Grade, ThirdMarks.Remark "
                        + "FROM tstudent, ThirdMarks "
                        + "WHERE tstudent.Stu_rno = ThirdMarks.Stu_rno AND tstudent.major='" + stumajor + "'";
            } else if (cbYear.getSelectedItem().equals("Fourth Year")) {
                sql = "SELECT  fourthstudent.Stu_rno, fourthstudent.stu_name, FourthMarks.Grade, FourthMarks.Remark "
                        + "FROM fourthstudent, FourthMarks "
                        + "WHERE fourthstudent.Stu_rno = FourthMarks.Stu_rno AND fourthstudent.major='" + stumajor + "'";
            } else {
                sql = "SELECT fifthstudent.Stu_rno, fifthstudent.stu_name, FifthMarks.Grade, FifthMarks.Remark "
                        + "FROM fifthstudent, FifthMarks "
                        + "WHERE fifthstudent.Stu_rno = FifthMarks.Stu_rno AND fifthstudent.major='" + stumajor + "'";
            }
            
            ResultSet rs = st.executeQuery(sql);
            taPrint.append("\t\t2023-2024 Student Result\n\n\n");
             taPrint.append("No.\tRoll No, \tStudent Name\tGrade\tRemark\n\n");
            
            
            int i =0;
            while (rs.next()) {
                taPrint.append(++i+"\t"+rs.getString(1)+" \t"+rs.getString(2)+"\t"+rs.getString(3)+"\t"+rs.getString(4)+"\n");
                
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdminWorkFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnStushowresActionPerformed

    private void cbMajorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMajorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMajorActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            taPrint.print();
        } catch (PrinterException ex) {
            Logger.getLogger(AdminWorkFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void cbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbYearActionPerformed

    private void btnStuMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStuMarksActionPerformed
///0000000000000000000000000000000000000000000000000000000000000000000000000000000
try {
    String sql;
    int total ;
    Connection con = DriverManager.getConnection("jdbc:sqlite:D:\\sqlite\\studentdb.db");
    Statement st = con.createStatement();
    String stumajor = (String) cbMajor.getSelectedItem();
    
    String rno = txtRno.getText();
    
    taPrint.setText(null);
    
    if (cbYear.getSelectedItem().equals("First Year")) {
        sql = "SELECT fstudent.Stu_rno, fstudent.stu_name, FirstMarks.Sub1, FirstMarks.Sub2, FirstMarks.Sub3, FirstMarks.Sub4, FirstMarks.Sub5, FirstMarks.Grade, FirstMarks.Remark "
            + "FROM fstudent, FirstMarks "
            + "WHERE fstudent.Stu_rno = FirstMarks.Stu_rno AND fstudent.Stu_rno='" + rno + "'";
    } else if (cbYear.getSelectedItem().equals("Second Year")) {
        sql = "SELECT sstudent.Stu_rno, sstudent.stu_name, SecondMarks.Sub1, SecondMarks.Sub2, SecondMarks.Sub3, SecondMarks.Sub4, SecondMarks.Sub5, SecondMarks.Grade, SecondMarks.Remark "
            + "FROM sstudent, SecondMarks "
            + "WHERE sstudent.Stu_rno = SecondMarks.Stu_rno AND sstudent.Stu_rno='" + rno + "'";
    } else if (cbYear.getSelectedItem().equals("Third Year")) {
        sql = "SELECT tstudent.Stu_rno, tstudent.stu_name, ThirdMarks.Sub1, ThirdMarks.Sub2, ThirdMarks.Sub3, ThirdMarks.Sub4, ThirdMarks.Sub5, ThirdMarks.Grade, ThirdMarks.Remark "
            + "FROM tstudent, ThirdMarks "
            + "WHERE tstudent.Stu_rno = ThirdMarks.Stu_rno AND tstudent.Stu_rno='" + rno + "'";
    } else if (cbYear.getSelectedItem().equals("Fourth Year")) {
        sql = "SELECT fourthstudent.Stu_rno, fourthstudent.stu_name, FourthMarks.Sub1, FourthMarks.Sub2, FourthMarks.Sub3, FourthMarks.Sub4, FourthMarks.Sub5, FourthMarks.Grade, FourthMarks.Remark "
            + "FROM fourthstudent, FourthMarks "
            + "WHERE fourthstudent.Stu_rno = FourthMarks.Stu_rno AND fourthstudent.Stu_rno='" + rno + "'";
    } else {
        sql = "SELECT fifthstudent.Stu_rno, fifthstudent.stu_name, FifthMarks.Sub1, FifthMarks.Sub2, FifthMarks.Sub3, FifthMarks.Sub4, FifthMarks.Sub5, FifthMarks.Grade, FifthMarks.Remark "
            + "FROM fifthstudent, FifthMarks "
            + "WHERE fifthstudent.Stu_rno = FifthMarks.Stu_rno AND fifthstudent.Stu_rno='" + rno + "'";
    }
    
    ResultSet rs = st.executeQuery(sql);
    taPrint.append("\tDEDAYE CYBER AREA\n\n\n");
    taPrint.append("\tMARKS CERTIFICATE\n\n");

    int i = 0;
    
    while (rs.next()) {
        
        taPrint.append("Student Roll No.\t" + rs.getString(1) + "\n");
        taPrint.append("Student Name  \t\t" + rs.getString(2) + "\n\n");
        taPrint.append("\tMARK OBTAINED\n\n");
        if (stumajor.equals("SE")) {
            taPrint.append("Java\t" + rs.getString(3) + "\t" + testGrade(rs.getString(3)) + "\n");
            taPrint.append("Kotlin\t" + rs.getString(4) + "\t" + testGrade(rs.getString(4)) + "\n");
            taPrint.append("Flutter\t" + rs.getString(5) + "\t" + testGrade(rs.getString(5)) + "\n");
            taPrint.append("Tools\t" + rs.getString(6) + "\t" + testGrade(rs.getString(6)) + "\n");
            taPrint.append("UI\t" + rs.getString(7) + "\t" + testGrade(rs.getString(7)) + "\n");
        } else if (stumajor.equals("KE")) {
            taPrint.append("Vision\t" + rs.getString(3) + "\t" + testGrade(rs.getString(3)) + "\n");
            taPrint.append("Python\t" + rs.getString(4) + "\t" + testGrade(rs.getString(4)) + "\n");
            taPrint.append("Bash\t" + rs.getString(5) + "\t" + testGrade(rs.getString(5)) + "\n");
            taPrint.append("Automation\t" + rs.getString(6) + "\t" + testGrade(rs.getString(6)) + "\n");
            taPrint.append("Robot \t" + rs.getString(7) + "\t" + testGrade(rs.getString(7)) + "\n");
        } else if (stumajor.equals("BIS")) {
            taPrint.append("Eco\t" + rs.getString(3) + "\t" + testGrade(rs.getString(3)) + "\n");
            taPrint.append("Business\t" + rs.getString(4) + "\t" + testGrade(rs.getString(4)) + "\n");
            taPrint.append("Counting\t" + rs.getString(5) + "\t" + testGrade(rs.getString(5)) + "\n");
            taPrint.append("Calculation\t" + rs.getString(6) + "\t" + testGrade(rs.getString(6)) + "\n");
            taPrint.append("Bankk\t" + rs.getString(7) + "\t" + testGrade(rs.getString(7)) + "\n");
        } else if (stumajor.equals("HPC")) {
            taPrint.append("Cloud\t" + rs.getString(3) + "\t" + testGrade(rs.getString(3)) + "\n");
            taPrint.append("HCI\t" + rs.getString(4) + "\t" + testGrade(rs.getString(4)) + "\n");
            taPrint.append("GO\t" + rs.getString(5) + "\t" + testGrade(rs.getString(5)) + "\n");
            taPrint.append("RUBY\t" + rs.getString(6) + "\t" + testGrade(rs.getString(6)) + "\n");
            taPrint.append("Arduino\t" + rs.getString(7) + "\t" + testGrade(rs.getString(7)) + "\n");
        } else if (stumajor.equals("CN")) {
            taPrint.append("System\t" + rs.getString(3) + "\t" + testGrade(rs.getString(3)) + "\n");
            taPrint.append("Routing\t" + rs.getString(4) + "\t" + testGrade(rs.getString(4)) + "\n");
            taPrint.append("Linux\t" + rs.getString(5) + "\t" + testGrade(rs.getString(5)) + "\n");
            taPrint.append("Solarise\t" + rs.getString(6) + "\t" + testGrade(rs.getString(6)) + "\n");
            taPrint.append("CCAR \t" + rs.getString(7) + "\t" + testGrade(rs.getString(7)) + "\n");
        } else {
            taPrint.append("Hacking\t" + rs.getString(3) + "\t" + testGrade(rs.getString(3)) + "\n");
            taPrint.append("Firewall\t" + rs.getString(4) + "\t" + testGrade(rs.getString(4)) + "\n");
            taPrint.append("Security\t" + rs.getString(5) + "\t" + testGrade(rs.getString(5)) + "\n");
            taPrint.append("Crypto\t" + rs.getString(6) + "\t" + testGrade(rs.getString(6)) + "\n");
            taPrint.append("BlockChain\t" + rs.getString(7) + "\t" + testGrade(rs.getString(7)) + "\n");
        }

// total = Integer.parseInt(rs.getString(3))+Integer.parseInt(rs.getString(4))+Integer.parseInt(rs.getString(5))+Integer.parseInt(rs.getString(6)+ Integer.valueOf(rs.getString(7));

        total = Integer.parseInt(rs.getString(3))
                + Integer.parseInt(rs.getString(4))
                + Integer.parseInt(rs.getString(5))
                + Integer.parseInt(rs.getString(6))
                + Integer.parseInt(rs.getString(7));


        taPrint.append("-------------------------------------------\n");
        taPrint.append("Total\t"+total+"\t"+rs.getString(8));
        
    }
    con.close();
} catch (SQLException ex) {
    Logger.getLogger(TrWorkFrame.class.getName()).log(Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_btnStuMarksActionPerformed
//to add test Grade
//============================================================================================================
//==============================================================================================================
    
    String testGrade(String marks) {
        int m = Integer.parseInt(marks);
        String grade;
        if ((m >= 80) && (m <= 100)) {
            grade = "A";
        } else if ((m >= 70) && (m <= 80)) {
            grade = "B";
        } else if ((m >= 60) && (m <= 70)) {
            grade = "C";
        } else if ((m >= 50) && (m <= 60)) {
            grade = "D";
        } else if ((m >= 40) && (m <= 50)) {
            grade = "E";
        } else {
            grade = "F";
        }

        return grade;
    }

//0000000000000000000000000000000000000000000000000000000000000000000000000
    
    
    
    
    
    private void txtRnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRnoActionPerformed
             
    
    /**
     * @param args the command line arguments
     */
    public  static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWorkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWorkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWorkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWorkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWorkFrame().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnStuMarks;
    private javax.swing.JButton btnStushowres;
    private javax.swing.JComboBox<String> cbMajor;
    private javax.swing.JComboBox<String> cbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taPrint;
    private javax.swing.JTextField txtRno;
    // End of variables declaration//GEN-END:variables
}
