/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.com;

//import java.sql.*;
import javax.swing.table.DefaultTableModel;
//import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
//import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
//////////
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
////////
//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import java.sql.SQLException;
//import javax.swing.table.DefaultTableModel;
//import javax.swing.JTable;

//import java.util.logging.Level;
//import java.util.logging.Logger;


public class StaffWorkFrame2 extends javax.swing.JFrame {

    private Object con;

    /**
     * Creates new form StaffWorkFrame2
     */
    public StaffWorkFrame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableStuShow = new javax.swing.JTable();
        btnMajor = new javax.swing.JPanel();
        cbYear = new javax.swing.JComboBox<>();
        btnStuShow = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtRno = new javax.swing.JTextField();
        btnRno = new javax.swing.JButton();
        btnStuAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnMajorr = new javax.swing.JButton();
        cbMajor = new javax.swing.JComboBox<>();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        TableStuShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Year", "Roll NO", "Major", "Date of Birth", "NRC", "Father Name", "Address", "Ph No:", "Gmail"
            }
        ));
        jScrollPane1.setViewportView(TableStuShow);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnMajor.setBackground(new java.awt.Color(0, 153, 153));

        cbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Year", "First Year", "Second Year", "Third Year", "Fourth Year", "Fifth Year", " " }));
        cbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbYearActionPerformed(evt);
            }
        });

        btnStuShow.setText("Show Student List By Year");
        btnStuShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStuShowActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Enter Roll Number to Search");

        txtRno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRnoActionPerformed(evt);
            }
        });

        btnRno.setText("Search by Roll Number");
        btnRno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRnoActionPerformed(evt);
            }
        });

        btnStuAdd.setText("ADD New Student");
        btnStuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStuAddActionPerformed(evt);
            }
        });

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnMajorr.setText("Show Student List By Major");
        btnMajorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMajorrActionPerformed(evt);
            }
        });

        cbMajor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Major", "SE", "KE", "BIS", "HPC", "CN", "CS", " " }));
        cbMajor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMajorActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnMajorLayout = new javax.swing.GroupLayout(btnMajor);
        btnMajor.setLayout(btnMajorLayout);
        btnMajorLayout.setHorizontalGroup(
            btnMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMajorLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(btnMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbYear, 0, 139, Short.MAX_VALUE)
                    .addComponent(btnStuAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMajor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82)
                .addGroup(btnMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMajorr, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnStuShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(btnMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnMajorLayout.createSequentialGroup()
                        .addGroup(btnMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMajorLayout.createSequentialGroup()
                                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addComponent(btnHome))
                        .addGap(256, 256, 256)
                        .addComponent(txtRno, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRno)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMajorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(175, 175, 175))))
        );
        btnMajorLayout.setVerticalGroup(
            btnMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMajorLayout.createSequentialGroup()
                .addGroup(btnMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnMajorLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(btnMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRno, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRno, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMajorLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(btnMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbYear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(btnStuShow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(btnMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStuAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(btnMajorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMajorr, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(cbMajor))))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnMajor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStuAddActionPerformed

        // TODO add your handling code here:
        new StaffWorkFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnStuAddActionPerformed

    private void btnStuShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStuShowActionPerformed
     
        //////////////////////////////
        try {
            //Part 5
            // show student list by YEar 

            // TODO add your handling code here:this htis aung moe myint
            DefaultTableModel tmodel = (DefaultTableModel) TableStuShow.getModel();
            tmodel.setRowCount(0);
            String[] data = new String[10];
            String sql = " ";
            String url = "jdbc:sqlite:D:\\sqlite\\studentdb.db";
            //java.sql.Connection con;
            Connection con = null;
            try {
                con = DriverManager.getConnection(url);
            } catch (SQLException ex) {
                Logger.getLogger(StaffWorkFrame2.class.getName()).log(Level.SEVERE, null, ex);
            }

            Statement st = con.createStatement();
            if (cbYear.getSelectedItem().equals("First Year")) {
                sql = "SELECT * FROM fstudent";
            } else if (cbYear.getSelectedItem().equals("Second Year")) {
                sql = "SELECT * FROM sstudent";
            } else if (cbYear.getSelectedItem().equals("Third Year")) {
                sql = "SELECT * FROM tstudent";
            } else if (cbYear.getSelectedItem().equals("Fourth Year")) {
                sql = "SELECT * FROM fourthstudent";
            } else {
                sql = "SELECT * FROM fifthstudent";
            }
            ResultSet rs = st.executeQuery(sql);;

            try {
                while (rs.next()) {
                    data[0] = rs.getString(1);
                    data[1] = rs.getString(2);
                    data[2] = rs.getString(3);
                    data[3] = rs.getString(4);
                    data[4] = rs.getString(5);
                    data[5] = rs.getString(6);
                    data[6] = rs.getString(7);
                    data[7] = rs.getString(8);
                    data[8] = rs.getString(9);
                    data[9] = rs.getString(10);

                    tmodel.addRow(data);
                }

                con.close();

            } catch (SQLException ex) {
                Logger.getLogger(StaffWorkFrame2.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (SQLException ex) {
            Logger.getLogger(StaffWorkFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnStuShowActionPerformed
////==================================================
    private void btnMajorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMajorrActionPerformed
         DefaultTableModel tmodel = (DefaultTableModel) TableStuShow.getModel();
    tmodel.setRowCount(0); // Clear existing rows

    String url = "jdbc:sqlite:D:\\sqlite\\studentdb.db";
    Connection con = null;
    PreparedStatement pstat = null;
    ResultSet rs = null;

    try {
        con = DriverManager.getConnection(url);

        String[] data = new String[10];
        String sql;
        String major = (String) cbMajor.getSelectedItem();

        // Determine SQL query based on selected year
        if (cbYear.getSelectedItem().equals("First Year")) {
            sql = "SELECT * FROM fstudent";
        } else if (cbYear.getSelectedItem().equals("Second Year")) {
            sql = "SELECT * FROM sstudent";
        } else if (cbYear.getSelectedItem().equals("Third Year")) {
            sql = "SELECT * FROM tstudent";
        } else if (cbYear.getSelectedItem().equals("Fourth Year")) {
            sql = "SELECT * FROM fourthstudent";
        } else {
            sql = "SELECT * FROM fifthstudent";
        }

        // Execute SQL query
        pstat = con.prepareStatement(sql);
        rs = pstat.executeQuery();

        // Apply sequential filtering
        while (rs.next()) {
            String recordMajor = rs.getString("major"); // Assuming 'major' is a column in the result set

            if (major.equals(recordMajor)) {
                for (int i = 1; i <= 10; i++) {
                    data[i - 1] = rs.getString(i); // Adjust index to match column count
                }
                tmodel.addRow(data);
            }
        }

    } catch (SQLException ex) {
        Logger.getLogger(StaffWorkFrame2.class.getName()).log(Level.SEVERE, null, ex);
    } finally {
        try {
            if (rs != null) rs.close();
            if (pstat != null) pstat.close();
            if (con != null) con.close();
        } catch (SQLException e) {
            Logger.getLogger(StaffWorkFrame2.class.getName()).log(Level.SEVERE, null, e);
        }
    }
       ///////////////////////////////////// /////////////////////////////////
//        try {
//            PreparedStatement pstat ;
//            Connection con;
//            String url="jdbc:sqlite:D:\\sqlite\\studentdb.db";
//            con = DriverManager.getConnection(url);
//
//            DefaultTableModel tmodel = (DefaultTableModel) TableStuShow.getModel();
//            tmodel.setRowCount(0);
//            String[] data = new String[10];
//            String sql="";
//             String major =(String)cbMajor.getSelectedItem();
//            //  PreparedStatement pstat;
//            if (cbYear.getSelectedItem().equals("First Year")) {
//                sql = "SELECT * FROM fstudent where major=?";
//            } else if (cbYear.getSelectedItem().equals("Second Year")) {
//                sql = "SELECT * FROM sstudent where major=?";
//            } else if (cbYear.getSelectedItem().equals("Third Year")) {
//                sql = "SELECT * FROM tstudent where major=?";
//            } else if (cbYear.getSelectedItem().equals("Fourth Year")) {
//                sql = "SELECT * FROM fourthstudent where major=?";
//            } else {
//                sql = "SELECT * FROM fifthstudent where major=?";
//            }
//            // Connection con = null;
//            
//            pstat = con.prepareStatement(sql);
//            // pstat = con.prepareCall(sql);
//            pstat.setString(1, major);
//            ResultSet rs = pstat.executeQuery();
//
//            while (rs.next()) {
//                data[0] = rs.getString(1);
//                data[1] = rs.getString(2);
//                data[2] = rs.getString(3);
//                data[3] = rs.getString(4);
//                data[4] = rs.getString(5);
//                data[5] = rs.getString(6);
//                data[6] = rs.getString(7);
//                data[7] = rs.getString(8);
//                data[8] = rs.getString(9);
//                data[9] = rs.getString(10);
//
//                tmodel.addRow(data);
//            }
//            con.close();
//        } catch (SQLException ex) {
//            Logger.getLogger(StaffWorkFrame2.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnMajorrActionPerformed

    private void txtRnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRnoActionPerformed

    private void btnRnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRnoActionPerformed
     

///00000000000000000000000000000000000000000000000000000000000000000000000000
        String url = "jdbc:sqlite:D:\\sqlite\\studentdb.db";
    
    // Initialize database resources
    Connection con = null;
    PreparedStatement pstat = null;
    ResultSet rs = null;

    try {
        // Step 1: Establish the database connection
        con = DriverManager.getConnection(url);

        // Step 2: Prepare the SQL query based on the selected year
        String sql = getSQLQueryBasedOnYear(cbYear.getSelectedItem().toString());
        pstat = con.prepareStatement(sql);

        // Step 3: Set the parameter for the SQL query
        String rno = txtRno.getText();
        pstat.setString(1, rno);

        // Step 4: Execute the SQL query
        rs = pstat.executeQuery();

        // Step 5: Clear previous data from the table model
        DefaultTableModel tmodel = (DefaultTableModel) TableStuShow.getModel();
        tmodel.setRowCount(0);

        // Step 6: Process the result set and populate the table model
        while (rs.next()) {
            Object[] rowData = new Object[10];
            for (int i = 0; i < 10; i++) {
                rowData[i] = rs.getObject(i + 1);
            }
            tmodel.addRow(rowData);
        }

    } catch (SQLException e) {
        // Handle SQL exceptions
        e.printStackTrace();
        // Optionally display an error message to the user
    } finally {
        // Step 7: Close all database resources
        closeResources(rs, pstat, con);
    }
}

/**
 * Returns the SQL query based on the selected year.
 */
private String getSQLQueryBasedOnYear(String year) {
    switch (year) {
        case "First Year":
            return "SELECT * FROM fstudent WHERE Stu_rno=?";
        case "Second Year":
            return "SELECT * FROM sstudent WHERE Stu_rno=?";
        case "Third Year":
            return "SELECT * FROM tstudent WHERE Stu_rno=?";
        case "Fourth Year":
            return "SELECT * FROM fourthstudent WHERE Stu_rno=?";
        default:
            return "SELECT * FROM fifthstudent WHERE Stu_rno=?";
    }
}

/**
 * Closes all database resources.
 */
private void closeResources(ResultSet rs, PreparedStatement pstat, Connection con) {
    try {
        if (rs != null) rs.close();
        if (pstat != null) pstat.close();
        if (con != null) con.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
//0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000        
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//        try {
//            String url="jdbc:sqlite:D:\\sqlite\\studentdb.db";
//            PreparedStatement pstat ;
//            Connection con = DriverManager.getConnection(url);
//
//            DefaultTableModel tmodel = (DefaultTableModel) TableStuShow.getModel();
//            tmodel.setRowCount(0);
//            String[] data = new String[10];
//            String sql="";
//            // String rno = txtRno.getText();
//          //  PreparedStatement pstat;
//            if (cbYear.getSelectedItem().equals("First Year")) {
//                sql = "SELECT * FROM fstudent where Stu_rno=?";
//            } else if (cbYear.getSelectedItem().equals("Second Year")) {
//                sql = "SELECT * FROM sstudent where Stu_rno=?";
//            } else if (cbYear.getSelectedItem().equals("Third Year")) {
//                sql = "SELECT * FROM tstudent where Stu_rno=?";
//            } else if (cbYear.getSelectedItem().equals("Fourth Year")) {
//                sql = "SELECT * FROM fourthstudent where Stu_rno=?";
//            } else {
//                sql = "SELECT * FROM fifthstudent where Stu_rno=?";
//            }
//            // Connection con = null;
//            
//             pstat = con.prepareStatement(sql);
//            // pstat = con.prepareCall(sql);
//            pstat.setString(1, txtRno.getText());
//            ResultSet rs = pstat.executeQuery();
//
//            while (rs.next()) {
//                data[0] = rs.getString(1);
//                data[1] = rs.getString(2);
//                data[2] = rs.getString(3);
//                data[3] = rs.getString(4);
//                data[4] = rs.getString(5);
//                data[5] = rs.getString(6);
//                data[6] = rs.getString(7);
//                data[7] = rs.getString(8);
//                data[8] = rs.getString(9);
//                data[9] = rs.getString(10);
//
//                tmodel.addRow(data);
//            }
//            con.close();
//          
//
//        } catch (SQLException ex) {
//            Logger.getLogger(StaffWorkFrame2.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnRnoActionPerformed

    private void cbMajorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMajorActionPerformed
      
    }//GEN-LAST:event_cbMajorActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        try { 
           //String url = null;
            // TODO add your handling code here:
          //  String url="";
            
            String url="jdbc:sqlite:D:\\sqlite\\studentdb.db";
            Connection con = DriverManager.getConnection(url);
            PreparedStatement pstat;
            String sql;
            DefaultTableModel tmodel = (DefaultTableModel) TableStuShow.getModel();
            int row = TableStuShow.getSelectedRow();
            String rno =  (String) TableStuShow.getModel().getValueAt(row, 2);
            System.out.println(rno);
            if (cbYear.getSelectedItem().equals("First Year")) {
                sql = "delete from fstudent where Stu_rno=?";
            } else if (cbYear.getSelectedItem().equals("Second Year")) {
                sql = "delete from sstudent where Stu_rno=?";
            } else if (cbYear.getSelectedItem().equals("Third Year")) {
                sql = "delete from tstudent where Stu_rno=?";
            } else if (cbYear.getSelectedItem().equals("Fourth Year")) {
                sql = "delete from fourthstudent where Stu_rno=?";
            } else  {
                sql = "delete from fifthstudent where Stu_rno=?";
            }
              pstat=con.prepareStatement(sql);
          //  pstat=prepareStatement(sql);
            pstat.setString(1, rno);
            pstat.executeUpdate();
           tmodel.removeRow(row);
            JOptionPane.showMessageDialog(this, "Success Delete Row");
            con.close();
           
 
       
        } catch (SQLException ex) {
            Logger.getLogger(StaffWorkFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnDelActionPerformed

    private void cbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbYearActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            String url = "jdbc:sqlite:D:\\sqlite\\studentdb.db";
            Connection con = DriverManager.getConnection(url);
            PreparedStatement pstat;
            String sql;
            DefaultTableModel tmodel = (DefaultTableModel) TableStuShow.getModel();
            int row = TableStuShow.getSelectedRow();
            String name = (String) TableStuShow.getModel().getValueAt(row, 0);
            String year = (String) TableStuShow.getModel().getValueAt(row, 1);
            String rno= (String) TableStuShow.getModel().getValueAt(row, 2);
            String major = (String) TableStuShow.getModel().getValueAt(row, 3);
            String dob = (String) TableStuShow.getModel().getValueAt(row, 4);
            String nrc = (String) TableStuShow.getModel().getValueAt(row, 5);
            String gmail = (String) TableStuShow.getModel().getValueAt(row, 6);
            String fname = (String) TableStuShow.getModel().getValueAt(row, 7);
            String address = (String) TableStuShow.getModel().getValueAt(row, 8);
            String phno = (String) TableStuShow.getModel().getValueAt(row, 9);
          // System.out.println(rno);
            if (cbYear.getSelectedItem().equals("First Year")) {
                sql = "update fstudent set stu_name=?, year=?,major=?, DOB=?, NRC=?, gmail=?, fname=?,address=?, phno=? where Stu_rno=? ";
            } else if (cbYear.getSelectedItem().equals("Second Year")) {
                sql = "update sstudent set stu_name=?, year=?,major=?, DOB=?, NRC=?, gmail=?, fname=?,address=? ,phno=? where Stu_rno=? ";
            } else if (cbYear.getSelectedItem().equals("Third Year")) {
                sql = "update tstudent set stu_name=?, year=?,major=?, DOB=?, NRC=?, gmail=?, fname=?,address=?, phno=? where Stu_rno=? ";
            } else if (cbYear.getSelectedItem().equals("Fourth Year")) {
                sql = "update fourthstudent set stu_name=?, year=?,major=?, DOB=?, NRC=?, gmail=?, fname=?,address=?, phno=? where Stu_rno=? ";
            } else {
                sql ="update fifthstudent set stu_name=?, year=?,major=?, DOB=?, NRC=?, gmail=?, fname=?,address=?, phno=? where Stu_rno=? ";
            }
            //pstat = con.prepareStatement(sql);
            pstat = con.prepareStatement(sql);
//  pstat=prepareStatement(sql);
           
            pstat.setString(1, name);
            pstat.setString(2, year);
            pstat.setString(3, major);
            pstat.setString(4, dob);
            pstat.setString(5, nrc);
            pstat.setString(6, gmail);
            pstat.setString(7, fname);
            pstat.setString(8, address);
            pstat.setString(9, phno);
            pstat.setString(10, rno);
            
            pstat.executeUpdate();
           // tmodel.removeRow(row);
            JOptionPane.showMessageDialog(this, "Success Update Row");
           
con.close();
        } catch (SQLException ex) {
            Logger.getLogger(StaffWorkFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffWorkFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffWorkFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffWorkFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffWorkFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new StaffWorkFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableStuShow;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHome;
    private javax.swing.JPanel btnMajor;
    private javax.swing.JButton btnMajorr;
    private javax.swing.JButton btnRno;
    private javax.swing.JButton btnStuAdd;
    private javax.swing.JButton btnStuShow;
    private javax.swing.JComboBox<String> cbMajor;
    private javax.swing.JComboBox<String> cbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtRno;
    // End of variables declaration//GEN-END:variables
//private void deleteRow(int rowIndex
    private void Statement(String sql) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private Connection getConnection() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private PreparedStatement prepareStatement(String sql) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
//
// java.lang.UnsupportedOperationException
//public Student() {
//    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//}
//public void deleteRow(int rowIndex) {
//    throw new UnsupportedOperationException("Not supported yet.");
//}
