/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.com;

//import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;


/**
 *
 * @author USER
 */
public class TrWorkFrame extends javax.swing.JFrame {

    private Object BIS;
    private Object KE;
    private Object SE;
    private Object HPC;
    private Object NE;
    private Object CS;

    /**
     * Creates new form TrWorkFrame
     */
    public TrWorkFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableStuShow = new javax.swing.JTable();
        cbYear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSub1 = new javax.swing.JLabel();
        lblSub2 = new javax.swing.JLabel();
        lblSub3 = new javax.swing.JLabel();
        lblSub4 = new javax.swing.JLabel();
        lblSub5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbYearz = new javax.swing.JComboBox<>();
        cbMajor = new javax.swing.JComboBox<>();
        txtRno = new javax.swing.JTextField();
        txtSub1 = new javax.swing.JTextField();
        txtSub2 = new javax.swing.JTextField();
        txtSub3 = new javax.swing.JTextField();
        txtSub4 = new javax.swing.JTextField();
        txtSub5 = new javax.swing.JTextField();
        txtGrade = new javax.swing.JTextField();
        txtRemark = new javax.swing.JTextField();
        btnshowstudent = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TrWorkingArea");
        setBackground(new java.awt.Color(255, 255, 0));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teacher Working Area", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TABValli", 1, 18))); // NOI18N

        TableStuShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No:", "Roll No:", "Student Name", "Subject", "Subject", "Subject", "Subject", "Subject", "Grade", "Remark"
            }
        ));
        jScrollPane1.setViewportView(TableStuShow);

        cbYear.setBackground(new java.awt.Color(0, 204, 204));
        cbYear.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculation Area", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel1.setText("Roll No:");

        lblSub1.setText("Subject 1");

        lblSub2.setText("Subject2");

        lblSub3.setText("Subject3");

        lblSub4.setText("Subject4");

        lblSub5.setText("Subject5");

        jLabel7.setText("Grade ");

        jLabel8.setText("Remark");

        cbYearz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Year", "First Year", "Second Year", "Third Year", "Fourth Year", "Fifth Year" }));
        cbYearz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbYearzActionPerformed(evt);
            }
        });

        cbMajor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Major", "SE", "KE", "BIS", "HPC", "CN", "CS" }));
        cbMajor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMajorItemStateChanged(evt);
            }
        });
        cbMajor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMajorActionPerformed(evt);
            }
        });

        txtRno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRnoActionPerformed(evt);
            }
        });

        txtGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradeActionPerformed(evt);
            }
        });

        btnshowstudent.setText("Show Student");
        btnshowstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowstudentActionPerformed(evt);
            }
        });

        btnSave.setText("Insert");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCal.setText("Calculate");
        btnCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalActionPerformed(evt);
            }
        });

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cbYearLayout = new javax.swing.GroupLayout(cbYear);
        cbYear.setLayout(cbYearLayout);
        cbYearLayout.setHorizontalGroup(
            cbYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbYearLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(cbYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbMajor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbYearz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(cbYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cbYearLayout.createSequentialGroup()
                        .addComponent(btnshowstudent)
                        .addGap(76, 76, 76)
                        .addComponent(btnSave)
                        .addGap(132, 132, 132)
                        .addComponent(btnClear)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(cbYearLayout.createSequentialGroup()
                        .addGroup(cbYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cbYearLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSub1)
                                .addGap(48, 48, 48)
                                .addComponent(lblSub2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(lblSub3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lblSub4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cbYearLayout.createSequentialGroup()
                                .addComponent(txtRno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSub1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(txtSub2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSub3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(txtSub4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(cbYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cbYearLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblSub5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(cbYearLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(txtSub5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(cbYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cbYearLayout.createSequentialGroup()
                                        .addComponent(btnCal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1))
                                    .addGroup(cbYearLayout.createSequentialGroup()
                                        .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(30, Short.MAX_VALUE))))))
        );
        cbYearLayout.setVerticalGroup(
            cbYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cbYearLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(cbYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(cbYearz, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSub1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSub2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSub3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSub4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSub5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cbYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSub4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSub5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRemark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cbYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnshowstudent)
                    .addComponent(btnSave)
                    .addComponent(btnClear)
                    .addComponent(btnCal)
                    .addComponent(jButton1))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMajorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMajorActionPerformed
        //Object CN = null;
       // Object CN = null;
       // Object SE = null;
        // TODO add your handling code here:
        if (cbMajor.getSelectedItem().equals("SE")) 
        {
            txtRno.setText("S-");
            lblSub1.setText("Java");
            lblSub2.setText("Kotlin");
            lblSub3.setText("Flutter");
            lblSub4.setText("Tools");
            lblSub5.setText("UI");
        } //Object KE = null;
        else if(cbMajor.getSelectedItem().equals("KE"))
        {
            txtRno.setText("K-");
            lblSub1.setText("Vision");
            lblSub2.setText("Python");
            lblSub3.setText("Bash");
            lblSub4.setText("Automation");
            lblSub5.setText("Robot");
        }
        else if(cbMajor.getSelectedItem().equals("BIS"))
        {
            txtRno.setText("B-");
            lblSub1.setText("Eco");
            lblSub2.setText("Business");
            lblSub3.setText("Counting");
            lblSub4.setText("Calculation");
            lblSub5.setText("Bankk");
        }
        else if(cbMajor.getSelectedItem().equals("HPC")){
            txtRno.setText("H-");
            lblSub1.setText("Cloud");
            lblSub2.setText("HCI");
            lblSub3.setText("GO");
            lblSub4.setText("RUBY");
            lblSub5.setText("Arduino");
        }
        else if(cbMajor.getSelectedItem().equals("CN")){
            txtRno.setText("N-");
            lblSub1.setText("System");
            lblSub2.setText("Routing");
            lblSub3.setText("Linux");
            lblSub4.setText("Solarise");
            lblSub5.setText("CCAR");
        }
         else{
            txtRno.setText("C-");
            lblSub1.setText("Hacking");
            lblSub2.setText("Firewall");
            lblSub3.setText("Security");
            lblSub4.setText("Crypto");
            lblSub5.setText("BlockChain");
        }
        
    }//GEN-LAST:event_cbMajorActionPerformed

    private void cbMajorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMajorItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMajorItemStateChanged

    private void txtRnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRnoActionPerformed

    private void btnCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalActionPerformed
        int sub1 = Integer.parseInt(txtSub1.getText());
        int sub2 = Integer.parseInt(txtSub2.getText());
        int sub3 = Integer.parseInt(txtSub3.getText());
        int sub4 = Integer.parseInt(txtSub4.getText());
        int sub5 = Integer.parseInt(txtSub5.getText());
     
        int avg = (sub1 + sub2 + sub3 + sub4 + sub5) / 5;
        if ((avg >= 80) && (avg <= 100)) {
            txtGrade.setText("A");
        } else if ((avg >= 70) && (avg <= 80)) {
            txtGrade.setText("B");
        } else if ((avg >= 60) && (avg <= 70)) {
            txtGrade.setText("C");
        } ////////////////////////////
        else if ((avg >= 50) && (avg <= 60)) {
            txtGrade.setText("D");
        } else if ((avg >= 40) && (avg <= 50)) {
            txtGrade.setText("E");
        } else {
            txtGrade.setText("F");
        }
        if ((sub1 >= 50) && (sub2 >= 50) && (sub3 >= 50) && (sub4 >= 50) && (sub5 >= 50))
            txtRemark.setText("Pass");
        else
            txtRemark.setText("Fail");
    }//GEN-LAST:event_btnCalActionPerformed

    private void txtGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradeActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    txtSub1.setText(null);
    txtSub2.setText(null);
    txtSub3.setText(null);
    txtSub4.setText(null);
    txtSub5.setText(null);
    txtRno.setText(null);
    txtRemark.setText(null);
    txtGrade.setText(null);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
           // Connection con;
            PreparedStatement pstat;
            String sql;
          Connection  con=DriverManager.getConnection("jdbc:sqlite:D:\\sqlite\\studentdb.db");
        //   if(cbYear.getSelectedItem().equals("First Year"))
               if(cbYearz.getSelectedItem().equals("First Year")){
               sql  = "insert into FirstMarks values(?,?,?,?,?,?,?,?,?)";
               }
            else  if(cbYearz.getSelectedItem().equals("Second Year")){
                sql  = "insert into SecondMarks values(?,?,?,?,?,?,?,?,?)";
            }
            else  if(cbYearz.getSelectedItem().equals("Third Year")){
                sql  = "insert into ThirdMarks values(?,?,?,?,?,?,?,?,?)";
            }
            else  if(cbYearz.getSelectedItem().equals("Fourth Year")){
                sql  = "insert into FourthMarks values(?,?,?,?,?,?,?,?,?)";
            }
            else
                sql  = "insert into FifthMarks values(?,?,?,?,?,?,?,?,?)";
            
            
            pstat = con.prepareStatement(sql);
            pstat.setString(1, null);
            pstat.setString(2, txtSub1.getText() );
            pstat.setString(3, txtSub2.getText() );
            pstat.setString(4, txtSub3.getText());
            pstat.setString(5, txtSub4.getText());
            pstat.setString(6,txtSub5.getText());
            pstat.setString(7,txtGrade.getText());
            pstat.setString(8,txtRemark.getText());
            pstat.setString(9,txtRno.getText());
            pstat.executeUpdate();
            con.close();
            
            JOptionPane.showMessageDialog(this, "Success Insert Row");
        } catch (SQLException ex) {
            Logger.getLogger(TrWorkFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbYearzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbYearzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbYearzActionPerformed

    private void btnshowstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowstudentActionPerformed
//        try {
//             Connection con;
//            DefaultTableModel tmodel = (DefaultTableModel) TableStuShow.getModel();
//            tmodel.setRowCount(0);
//            String[] data = new String[10];
//            String sql="";
//           
//            con=DriverManager.getConnection("jdbc:sqlite:D:\\sqlite\\studentdb.db");
//            Statement st = con.createStatement();
//            if(cbMajor.getSelectedItem().equals("SE"))
//            {
//                TableStuShow.getColumnModel().getColumn(3).setHeaderValue("Java");
//                TableStuShow.getColumnModel().getColumn(4).setHeaderValue("Kotlin");
//                TableStuShow.getColumnModel().getColumn(5).setHeaderValue("Flutter");
//                TableStuShow.getColumnModel().getColumn(6).setHeaderValue("Tools");
//                TableStuShow.getColumnModel().getColumn(7).setHeaderValue("UI");
//            }
//            else  if(cbMajor.getSelectedItem().equals("KE"))
//            {
//                TableStuShow.getColumnModel().getColumn(3).setHeaderValue("Vision");
//                TableStuShow.getColumnModel().getColumn(4).setHeaderValue("Python");
//                TableStuShow.getColumnModel().getColumn(5).setHeaderValue("Bash");
//                TableStuShow.getColumnModel().getColumn(6).setHeaderValue("Automation");
//                TableStuShow.getColumnModel().getColumn(7).setHeaderValue("Robot");
//            }
//           else   if(cbMajor.getSelectedItem().equals("BIS"))
//            {
//                TableStuShow.getColumnModel().getColumn(3).setHeaderValue("Eco");
//                TableStuShow.getColumnModel().getColumn(4).setHeaderValue("Business");
//                TableStuShow.getColumnModel().getColumn(5).setHeaderValue("Counting");
//                TableStuShow.getColumnModel().getColumn(6).setHeaderValue("Calculation");
//                TableStuShow.getColumnModel().getColumn(7).setHeaderValue("Bankk");
//            } 
//          else  if(cbMajor.getSelectedItem().equals("HPC"))
//            {
//                TableStuShow.getColumnModel().getColumn(3).setHeaderValue("Cloud");
//                TableStuShow.getColumnModel().getColumn(4).setHeaderValue("HCI");
//                TableStuShow.getColumnModel().getColumn(5).setHeaderValue("GO");
//                TableStuShow.getColumnModel().getColumn(6).setHeaderValue("RUBY");
//                TableStuShow.getColumnModel().getColumn(7).setHeaderValue("Arduino");
//            } 
//        else      if(cbMajor.getSelectedItem().equals("CN"))
//            {
//                TableStuShow.getColumnModel().getColumn(3).setHeaderValue("System");
//                TableStuShow.getColumnModel().getColumn(4).setHeaderValue("Routing");
//                TableStuShow.getColumnModel().getColumn(5).setHeaderValue("Linux");
//                TableStuShow.getColumnModel().getColumn(6).setHeaderValue("Solarise");
//                TableStuShow.getColumnModel().getColumn(7).setHeaderValue("CCAR");
//            } 
//           else  
//            {
//                TableStuShow.getColumnModel().getColumn(3).setHeaderValue("Hacking");
//                TableStuShow.getColumnModel().getColumn(4).setHeaderValue("Firewall");
//                TableStuShow.getColumnModel().getColumn(5).setHeaderValue("Security");
//                TableStuShow.getColumnModel().getColumn(6).setHeaderValue("Crypto");
//                TableStuShow.getColumnModel().getColumn(7).setHeaderValue("BlockChain");
//            } 
//            String stumajor = (String) cbMajor.getSelectedItem();
//            if (cbYearz.getSelectedItem().equals("First Year")) {
//                //  sql = "SELECT * FROM fstudent";
//                sql = "select FirstMarks.rowid,fstudent.Stu_rno,fstudent.stu_name,FirstMarks.Sub1,FirstMarks.Sub2,FirstMarks.Sub3,FirtMarks.Sub4,FirstMarks.Sub5,FirstMarks.Grade,FirstMarks.Remark from fstudent,FirstMarks where fstudent.Stu_rno=FirstMarks.Stu_rno and fstudent.major='"+stumajor+"'";
//           
//            } else if (cbYearz.getSelectedItem().equals("Second Year")) {
//                sql = "select SecondMarks.rowid,sstudent.Stu_rno,sstudent.stu_name,SecondMarks.Sub1,SecondMarks.Sub2,SecondMarks.Sub3,SecondMarks.Sub4,SecondMarks.Sub5,SecondMarks.Grade,SecondMarks.Remark from sstudent,SecondMarks where sstudent.Stu_rno=SecondMarks.Stu_rno and sstudent.major='"+stumajor+"'";
//           
//            } else if (cbYearz.getSelectedItem().equals("Third Year")) {
//                sql = "select ThirdMarks.rowid,tstudent.Stu_rno,fstudent.stu_name,ThirdMarks.Sub1,ThirdMarks.Sub2,ThirdMarks.Sub3,ThirdMarks.Sub4,ThirdMarks.Sub5,ThirdMarks.Grade,ThirdMarks.Remark from tstudent,ThirdMarks where tstudent.Stu_rno=ThirdMarks.Stu_rno and tstudent.major='"+stumajor+"'";
//            
//            } else if (cbYearz.getSelectedItem().equals("Fourth Year")) {
//                sql = "select FourthMarks.rowid,fourthstudent.Stu_rno,fourthstudent.stu_name,FourthMarks.Sub1,FourthMarks.Sub2,FourthMarks.Sub3,FourthMarks.Sub4,FourthMarks.Sub5,FourthtMarks.Grade,FourthMarks.Remark from fourthstudent,FourthMarks where fourthstudent.Stu_rno=FourthMarks.Stu_rno and fourthstudent.major='"+stumajor+"'";
//            
//            } else {
//                sql = "select FifthMarks.rowid,fifthstudent.Stu_rno,fifthstudent.stu_name,FifthMarks.Sub1,FifthMarks.Sub2,FifthMarks.Sub3,FifthMarks.Sub4,FifthMarks.Sub5,FifthMarks.Grade,FifthMarks.Remark from fifthstudent,FifthMarks where fifthstudent.Stu_rno=FifthMarks.Stu_rno and fifthstudent.major='"+stumajor+"'";
//            }
//                ResultSet rs = st.executeQuery(sql);;
//            
//                while (rs.next()) {
//                    data[0] = rs.getString(1);
//                    data[1] = rs.getString(2);
//                    data[2] = rs.getString(3);
//                    data[3] = rs.getString(4);
//                    data[4] = rs.getString(5);
//                    data[5] = rs.getString(6);
//                    data[6] = rs.getString(7);
//                    data[7] = rs.getString(8);
//                    data[8] = rs.getString(9);
//                    data[9] = rs.getString(10);
//
//                    tmodel.addRow(data);
//                }
//                    con.close();
//              
//              
//              
//              
//              
//              
//              
//            
//            ////////////////////////////////////////////////////
//            try {
//                con = DriverManager.getConnection(sql);
//            } catch (SQLException ex) {
//                Logger.getLogger(TrWorkFrame.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(TrWorkFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
                                              
    try {
        Connection con;
        DefaultTableModel tmodel = (DefaultTableModel) TableStuShow.getModel();
        tmodel.setRowCount(0);
        String[] data = new String[10];
        String sql = "";
        
        con = DriverManager.getConnection("jdbc:sqlite:D:\\sqlite\\studentdb.db");
        Statement st = con.createStatement();
        String stumajor = (String) cbMajor.getSelectedItem();
        
        if(cbMajor.getSelectedItem().equals("SE")) {
            TableStuShow.getColumnModel().getColumn(3).setHeaderValue("Java");
            TableStuShow.getColumnModel().getColumn(4).setHeaderValue("Kotlin");
            TableStuShow.getColumnModel().getColumn(5).setHeaderValue("Flutter");
            TableStuShow.getColumnModel().getColumn(6).setHeaderValue("Tools");
            TableStuShow.getColumnModel().getColumn(7).setHeaderValue("UI");
        } else if(cbMajor.getSelectedItem().equals("KE")) {
            TableStuShow.getColumnModel().getColumn(3).setHeaderValue("Vision");
            TableStuShow.getColumnModel().getColumn(4).setHeaderValue("Python");
            TableStuShow.getColumnModel().getColumn(5).setHeaderValue("Bash");
            TableStuShow.getColumnModel().getColumn(6).setHeaderValue("Automation");
            TableStuShow.getColumnModel().getColumn(7).setHeaderValue("Robot");
        } else if(cbMajor.getSelectedItem().equals("BIS")) {
            TableStuShow.getColumnModel().getColumn(3).setHeaderValue("Eco");
            TableStuShow.getColumnModel().getColumn(4).setHeaderValue("Business");
            TableStuShow.getColumnModel().getColumn(5).setHeaderValue("Counting");
            TableStuShow.getColumnModel().getColumn(6).setHeaderValue("Calculation");
            TableStuShow.getColumnModel().getColumn(7).setHeaderValue("Bankk");
        } else if(cbMajor.getSelectedItem().equals("HPC")) {
            TableStuShow.getColumnModel().getColumn(3).setHeaderValue("Cloud");
            TableStuShow.getColumnModel().getColumn(4).setHeaderValue("HCI");
            TableStuShow.getColumnModel().getColumn(5).setHeaderValue("GO");
            TableStuShow.getColumnModel().getColumn(6).setHeaderValue("RUBY");
            TableStuShow.getColumnModel().getColumn(7).setHeaderValue("Arduino");
        } else if(cbMajor.getSelectedItem().equals("CN")) {
            TableStuShow.getColumnModel().getColumn(3).setHeaderValue("System");
            TableStuShow.getColumnModel().getColumn(4).setHeaderValue("Routing");
            TableStuShow.getColumnModel().getColumn(5).setHeaderValue("Linux");
            TableStuShow.getColumnModel().getColumn(6).setHeaderValue("Solarise");
            TableStuShow.getColumnModel().getColumn(7).setHeaderValue("CCAR");
        } else {
            TableStuShow.getColumnModel().getColumn(3).setHeaderValue("Hacking");
            TableStuShow.getColumnModel().getColumn(4).setHeaderValue("Firewall");
            TableStuShow.getColumnModel().getColumn(5).setHeaderValue("Security");
            TableStuShow.getColumnModel().getColumn(6).setHeaderValue("Crypto");
            TableStuShow.getColumnModel().getColumn(7).setHeaderValue("BlockChain");
        }
         TableStuShow.getTableHeader().repaint();
         

        if (cbYearz.getSelectedItem().equals("First Year")) {
            sql = "SELECT FirstMarks.rowid, fstudent.Stu_rno, fstudent.stu_name, FirstMarks.Sub1, FirstMarks.Sub2, FirstMarks.Sub3, FirstMarks.Sub4, FirstMarks.Sub5, FirstMarks.Grade, FirstMarks.Remark " +
                  "FROM fstudent, FirstMarks " +
                  "WHERE fstudent.Stu_rno = FirstMarks.Stu_rno AND fstudent.major='" + stumajor + "'";
        } else if (cbYearz.getSelectedItem().equals("Second Year")) {
            sql = "SELECT SecondMarks.rowid, sstudent.Stu_rno, sstudent.stu_name, SecondMarks.Sub1, SecondMarks.Sub2, SecondMarks.Sub3, SecondMarks.Sub4, SecondMarks.Sub5, SecondMarks.Grade, SecondMarks.Remark " +
                  "FROM sstudent, SecondMarks " +
                  "WHERE sstudent.Stu_rno = SecondMarks.Stu_rno AND sstudent.major='" + stumajor + "'";
        } else if (cbYearz.getSelectedItem().equals("Third Year")) {
            sql = "SELECT ThirdMarks.rowid, tstudent.Stu_rno, tstudent.stu_name, ThirdMarks.Sub1, ThirdMarks.Sub2, ThirdMarks.Sub3, ThirdMarks.Sub4, ThirdMarks.Sub5, ThirdMarks.Grade, ThirdMarks.Remark " +
                  "FROM tstudent, ThirdMarks " +
                  "WHERE tstudent.Stu_rno = ThirdMarks.Stu_rno AND tstudent.major='" + stumajor + "'";
        } else if (cbYearz.getSelectedItem().equals("Fourth Year")) {
            sql = "SELECT FourthMarks.rowid, fourthstudent.Stu_rno, fourthstudent.stu_name, FourthMarks.Sub1, FourthMarks.Sub2, FourthMarks.Sub3, FourthMarks.Sub4, FourthMarks.Sub5, FourthMarks.Grade, FourthMarks.Remark " +
                  "FROM fourthstudent, FourthMarks " +
                  "WHERE fourthstudent.Stu_rno = FourthMarks.Stu_rno AND fourthstudent.major='" + stumajor + "'";
        } else {
            sql = "SELECT FifthMarks.rowid, fifthstudent.Stu_rno, fifthstudent.stu_name, FifthMarks.Sub1, FifthMarks.Sub2, FifthMarks.Sub3, FifthMarks.Sub4, FifthMarks.Sub5, FifthMarks.Grade, FifthMarks.Remark " +
                  "FROM fifthstudent, FifthMarks " +
                  "WHERE fifthstudent.Stu_rno = FifthMarks.Stu_rno AND fifthstudent.major='" + stumajor + "'";
        }
        
        ResultSet rs = st.executeQuery(sql);
        
        while (rs.next()) {
            data[0] = rs.getString(1);
            data[1] = rs.getString(2);
            data[2] = rs.getString(3);
            data[3] = rs.getString(4);
            data[4] = rs.getString(5);
            data[5] = rs.getString(6);
            data[6] = rs.getString(7);
            data[7] = rs.getString(8);
            data[8] = rs.getString(9);
            data[9] = rs.getString(10);

            tmodel.addRow(data);
        }
        con.close();

    } catch (SQLException ex) {
        Logger.getLogger(TrWorkFrame.class.getName()).log(Level.SEVERE, null, ex);
    }


    }//GEN-LAST:event_btnshowstudentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new LoginFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

       
    
//                }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrWorkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrWorkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrWorkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrWorkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrWorkFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableStuShow;
    private javax.swing.JButton btnCal;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnshowstudent;
    private javax.swing.JComboBox<String> cbMajor;
    private javax.swing.JPanel cbYear;
    private javax.swing.JComboBox<String> cbYearz;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSub1;
    private javax.swing.JLabel lblSub2;
    private javax.swing.JLabel lblSub3;
    private javax.swing.JLabel lblSub4;
    private javax.swing.JLabel lblSub5;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtRemark;
    private javax.swing.JTextField txtRno;
    private javax.swing.JTextField txtSub1;
    private javax.swing.JTextField txtSub2;
    private javax.swing.JTextField txtSub3;
    private javax.swing.JTextField txtSub4;
    private javax.swing.JTextField txtSub5;
    // End of variables declaration//GEN-END:variables

    private static class cbYear {

        private static Object getSelectedItem() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public cbYear() {
        }
    }
}
